[project]
name = "recipeai"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.13"
dependencies = [
    "httpx>=0.28.1",
    "langchain>=0.3.27",
    "langchain-openai>=0.3.30",
    "mcp>=1.13.0",
    "pydantic>=2.11.7",
    "tinydb>=4.8.2",
]
